<?php

use Illuminate\Database\Seeder;

class SeederTableDrugs extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
         //KOSONGKAN TABEL SISWA
         DB::table('drugs')->delete();
         //BUAT DATA BERUPA ARRAY
         $arrdrugs = array(
            array('Id'=>'1','Name'=>'Amoxsan','ImageUrl'=>'1.jpg','Desc'=>'Amoxsan merupakan obat antibiotika yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak serta demam tifoid pada anak.','Brand'=>'Amoxsan(caprifarmindo labs)','Type'=>'Antibiotika','AvgPrice'=>'Rp 4.372,- / Tablet','General'=>'Amoxsan merupakan obat antibiotika yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak serta demam tifoid pada anak. Amoxsan mengandung Amoksisilin (antibiotik golongan beta-laktam) yaitu obat golongan penisilin yang bersifat bakteriolitik bekerja dengan cara menghambat sintesis dinding sel bakteri dengan memutus rantai polimer peptidoglikan sehingga tidak terbentuk.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'2','Name'=>'Supramox','ImageUrl'=>'2.jpg','Desc'=>'supramox dapat digunakan untuk mengatasi infeksi yang disebakan oleh bakteri/mikroorganisme pada bagian pernafasan dan saluran kemih.','Brand'=>'Supramox(Meprofarm)','Type'=>'Antibiotika','AvgPrice'=>'Rp 29.397,- / Botol','General'=>' supramox dapat digunakan untuk mengatasi infeksi yang disebakan oleh bakteri/mikroorganisme pada bagian pernafasan dan saluran kemih. Bakteri atau mikroorganisme yang f terdapat pada bagian pencernaan dan saluran kemih yang dapat menyebabkan infeksi, sensitif terhadapa Amoxicillin  ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'3','Name'=>'Lapimox forte','ImageUrl'=>'3.png','Desc'=>'Lapimox mengandung zat aktif amoksisilin yang termasuk dalam golongan antibiotik spektrum luas, sehingga mampu membunuh bakteri gram + maupun -.','Brand'=>'Lapimox forte(LAPI)','Type'=>'Antibiotika','AvgPrice'=>'Rp 46.195,- / Botol','General'=>'Lapimox mengandung zat aktif amoksisilin yang termasuk dalam golongan antibiotik spektrum luas, sehingga mampu membunuh bakteri gram + maupun -. Amoksisilin diserap dengan baik dan cepat pada saluran pencernaan, oleh karena itu pemberian Lapimox bersamaan dengan makan agar dapat mengurangi rasa tidak nyaman di GI juga. Karena obat ini termasuk dalam golongan antibiotik, maka penggunaannya harus sesuai dengan resep dokter dan tidak boleh dihentikan sembarangan karena dapat menyebabkan terjadinya resistensi bakteri ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'4','Name'=>'Amoxicillin','ImageUrl'=>'4.jpg','Desc'=>'Amoxicillin Indo Farma merupakan obat antibiotika yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak  ','Brand'=>'Amoxicillin(indofarma)','Type'=>'Antibiotika','AvgPrice'=>'Rp 512,- / Tablet','General'=>'Amoxicillin Indo Farma merupakan obat antibiotika yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak. Amoksisilin (antibiotik golongan beta-laktam) adalah obat golongan penisilin yang bersifat bakteriolitik bekerja dengan cara menghambat sintesis dinding sel bakteri dengan memutus rantai polimer peptidoglikan sehingga tidak terbentuk','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'5','Name'=>'Sanpicillin','ImageUrl'=>'5.jpeg','Desc'=>'Sanpicillin mengandung Ampisilin trihidrat 500 mg, yang merupakan antibiotik golongan beta laktam, temasuk dalam keluarga penisilin dengan spektrum luas penghambatan bakteri.','Brand'=>'Sanpicillin(SANBE FARMA)','Type'=>'Antibiotika','AvgPrice'=>'Rp 2.282,- / Tablet','General'=>' Sanpicillin mengandung Ampisilin trihidrat 500 mg, yang merupakan antibiotik golongan beta laktam, temasuk dalam keluarga penisilin dengan spektrum luas penghambatan bakteri. Mekanisme kerja Sanpicillin yaitu dengan mengganggu proses pembentukan dinding sel bakteri, sehingga akan mengakibatkan kematian bakteri. Sanpicillin digunakan untuk mengobati infeksi saluran kemih, saluran nafas, saluran cerna, saluran empedu disebabkan bakteri gram positif dan negatif. Penggunaan Sanpicillin pada penderita gagal ginjal perlu diperhatikan dan dosis yang diberikan perlu disesuaikan, karena jangka panjang penggunaan Sanpisilin dapat menyebabkan nefrotoksisitas dan perubahan fungsi ginjal. Sanpicillin diproduksi oleh Sanbe Farma.  ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'6','Name'=>'Ampi','ImageUrl'=>'6.jpg','Desc'=>' Ampi dengan komposisi ampicillin merupakan antibiotik yang digunakan untuk mengobati infeksi yang disebabkan oleh bakteri yang peka seperti infeksi saluran nafas (otitis media akut, faringitis, sinusitis), endocarditis, meningitis, gonorrhoea, infeksi kulit dan jaringan lunak, Infeksi saluran kemih, infeksi Salmonella dan shigela ','Brand'=>'Ampi(Interbat)','Type'=>'Antibiotika','AvgPrice'=>'Rp 503,- / Tablet','General'=>'Ampi dengan komposisi ampicillin merupakan antibiotik yang digunakan untuk mengobati infeksi yang disebabkan oleh bakteri yang peka seperti infeksi saluran nafas (otitis media akut, faringitis, sinusitis), endocarditis, meningitis, gonorrhoea, infeksi kulit dan jaringan lunak, Infeksi saluran kemih, infeksi Salmonella dan shigela','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'7','Name'=>'Zibramax','ImageUrl'=>'7.jpg','Desc'=>'Zibramax 500mg diindikasikan untuk infeksi saluran nafas bagian atas dan bawah, kulit dan jaringan lunak, uretritis non gonokokal dan servisitis yang diakibatkan oleh Chlamydia trachomatis. ','Brand'=>'Zibramax(PT.Guardian Pharmatama.)','Type'=>'Antibiotika','AvgPrice'=>'Rp 50.395,- / Tablet','General'=>'  Zibramax 500mg diindikasikan untuk infeksi saluran nafas bagian atas dan bawah, kulit dan jaringan lunak, uretritis non gonokokal dan servisitis yang diakibatkan oleh Chlamydia trachomatis. ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'8','Name'=>'Ancla','ImageUrl'=>'8.jpg','Desc'=>'Ancla forte memiliki efektif untuk mengatasi infeksi saluran nafas, kulit dan jaringan, saluran kemih, tulang dan sendi, serta infeksi lainnya.','Brand'=>'Ancla (MEPROFARM)','Type'=>'Antibiotika','AvgPrice'=>'Rp 89.458,- / Botol','General'=>' Ancla sirup forte diproduksi oleh PT. Meprofarm dan telah terdaftar pada BPOM. Ancla forte disajikan dalam bentuk sirup kering yang perlu ditambahkan air hingga batas yang tertera pada botol dan kocok dahulu sebelum diberikan pada pasien. Ancla forte pada setiap 5ml nya mengandung 250mg amoxicilin trihydrate dan 62,5mg K clavulanat. Kombinasi dari kandungan tersebut efektif untuk mengatasi infeksi saluran nafas, kulit dan jaringan, saluran kemih, tulang dan sendi, serta infeksi lainnya.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'9','Name'=>'Clanexi forte','ImageUrl'=>'9.jpg','Desc'=>'Clanexi merupakan antibiotik kombinasi yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak. ','Brand'=>'Clanexi forte(sanbe farma)','Type'=>'Antibiotika','AvgPrice'=>'Rp 16.043,- / Tablet','General'=>'Clanexi merupakan antibiotik kombinasi yang digunakan untuk mengatasi infeksi pada saluran pernafasan atas, infeksi saluran kemih, saluran cerna, kulit dan jaringan lunak. Claneksi mengandung kombinasi Amoksisilin (antibiotik golongan beta-laktam) dengan Asam Klavulanat (penghambat enzim beta-laktamase) yang disebut coamoxiclav. Coamoxiclav bersifat bakteriolitik yang bekerja dengan cara menghambat sintesis dinding sel bakteri dengan memutus rantai polimer peptidoglikan sehingga tidak terbentuk. Kombinasi ini bertujuan untuk meningkatkan efektivitas antibiotik terhadap bakteri-baketri yang memproduksi beta-laktamase yang resisten terhadap Amoksisilin.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'10','Name'=>'Erysanbe','ImageUrl'=>'10.jpg','Desc'=>'Erysanbe merupakan antibiotik yang digunakan untuk mengatasi infeksi karena kuman yang peka terhadap eritromisin.','Brand'=>'Erysanbe (Sanbe)','Type'=>'Antibiotika','AvgPrice'=>'Rp 3.535,- / Tablet','General'=>'Erysanbe merupakan antibiotik yang digunakan untuk mengatasi infeksi karena kuman yang peka terhadap eritromisin.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'11','Name'=>'Opithrocyn','ImageUrl'=>'11.jpg','Desc'=>'Sirup obat antibiotik golongan makrolid yang dapat membantu mengatasi berbagai infeksi bakteri','Brand'=>'Opithrocyn(Otto Pharmacetical Laboratories.)','Type'=>'Antibiotika','AvgPrice'=>'Rp 34.997,- / Botol','General'=>'Sirup obat antibiotik golongan makrolid yang dapat membantu mengatasi berbagai infeksi bakteri','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'12','Name'=>'Sanprima','ImageUrl'=>'12.jpg','Desc'=>'Sanprima Forte merupakan obat antibiotika kombinasi yang digunakan untuk mengobati infeksi akibat bakteri pada saluran pernapasan, pencernaan, dan saluran kemih.','Brand'=>'Sanprima(sanbe farma)','Type'=>'Antibiotika','AvgPrice'=>'Rp 2.653,- / Tablet','General'=>'Sanprima Forte merupakan obat antibiotika kombinasi yang digunakan untuk mengobati infeksi akibat bakteri pada saluran pernapasan, pencernaan, dan saluran kemih. Sanprima Forte mengandung kombinasi dari antibiotik Trimethoprim dan Sulfamethoxazole yang dikenal sebagai Cotrimoxazole. Cotrimoxazole memiliki sifat bakterisida atau dapat membunuh bakteri dengan cara menghambat enzim metabolisme asam folat pada bakteri yang peka. Cotrimoxazole dapat digunakan untuk mengobati infeksi bakteri yang resisten terhadap Sulfamethoxazole tetapi masih peka terhadap Trimethoprim.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'13','Name'=>'Sanmol','ImageUrl'=>'13.jpg','Desc'=>'Sanmol Drop merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada bayi dan anak-anak. ','Brand'=>'Sanmol(sanbe farma)','Type'=>'Analgetik – Antipiretik','AvgPrice'=>'Rp 20.364,- / Botol','General'=>'Sanmol Drop merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada bayi dan anak-anak. Setiap 0,6 ml Sanmol Drop mengandung zat aktif Paracetamol (Acetaminophen) yaitu zat aktif yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bekerja dengan cara menghambat pembentukan prostaglandin yaitu zat yang memicu nyeri dan demam di hipotalamus untuk meningkatkan pelepasan panas supaya suhu tubuh normal.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'14','Name'=>'Naprex','ImageUrl'=>'14.jpg','Desc'=>'Naprex Sirup merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada anak-anak.','Brand'=>'Naprex(Darya Varia)','Type'=>'Analgetik – Antipiretik','AvgPrice'=>'Rp 50.996,- / Botol','General'=>'Naprex Sirup merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada anak-anak. Naprex Sirup mengandung zat aktif Paracetamol (Acetaminophen) yaitu zat aktif yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bekerja dengan cara menghambat pembentukan prostaglandin yaitu zat yang memicu nyeri dan demam di hipotalamus untuk meningkatkan pelepasan panas supaya suhu tubuh normal. ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'15','Name'=>'Praxion','ImageUrl'=>'15.jpg','Desc'=>'Praxion Sirup merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada anak-anak.','Brand'=>'Praxion(pharos)','Type'=>'Analgetik – Antipiretik','AvgPrice'=>'Rp 30.866,- / Botol','General'=>'Praxion Sirup merupakan obat yang digunakan untuk meredakan demam dan rasa nyeri atau sakit kepala pada anak-anak. Setiap 5 ml Praxion Sirup mengandung zat aktif Paracetamol (Acetaminophen) yaitu zat aktif yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bekerja dengan cara menghambat pembentukan prostaglandin yaitu zat yang memicu nyeri dan demam di hipotalamus untuk meningkatkan pelepasan panas supaya suhu tubuh normal.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'16','Name'=>'Propyretic','ImageUrl'=>'16.jpeg','Desc'=>'Propyretic Supp merupakan obat dalam bentuk suppositoria berfungsi dalam meredakan demam dan rasa nyeri.','Brand'=>'Propyretic(Combiphar)','Type'=>'Analgetik – Antipiretik','AvgPrice'=>'Rp 8.888,- / Tablet','General'=>'Propyretic Supp merupakan obat dalam bentuk suppositoria berfungsi dalam meredakan demam dan rasa nyeri. Panadol mengandung zat aktif Paracetamol yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik dengan menghambat pembentukan prostaglandin (zat yang dilepaskan tubuh sebagai reaksi terhadap kerusakan jaringan dan memicu terjadinya demam, peradangan, dan rasa nyeri).','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'17','Name'=>'Bufect','ImageUrl'=>'17.png','Desc'=>'bufet Ibuprofen merupakan golongan obat antiinflamasi golongan nonsteroidal yang mempunyai efek sebagai analgesik (meringankan rasa sakit) dan antipiretik (menurunkan demam). ','Brand'=>'Bufect (PT. Sanbe Farma)','Type'=>'Analgetik – Antipiretik','AvgPrice'=>'Rp 18.520,- / Botol','General'=>'bufet Ibuprofen merupakan golongan obat antiinflamasi golongan nonsteroidal yang mempunyai efek sebagai analgesik (meringankan rasa sakit) dan antipiretik (menurunkan demam). ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'18','Name'=>'Proris','ImageUrl'=>'18.jpg','Desc'=>'Proris adalah obat yang digunakan sebagai pereda demam, nyeri ringan khususnya ketika pasien juga mengalami peradangan, dan mengurangi gangguan inflamasi (peradangan) secara umum.','Brand'=>'Proris(pharos)','Type'=>'Antibiotika','AvgPrice'=>'Rp 30.360,- / Botol ','General'=>'Proris adalah obat yang digunakan sebagai pereda demam, nyeri ringan khususnya ketika pasien juga mengalami peradangan, dan mengurangi gangguan inflamasi (peradangan) secara umum. Setiap 5 ml Proris mengandung zat aktif Ibuprofen yang termasuk dalam golongan Nonsteroidal Anti-Inflammatory Drug (NSAID) dan memiliki mekanisme kerja sebagai berikut: Menghambat kerja dari enzim siklooksigenasi (COX) dimana enzim ini berfungsi dalam membantu pembentukan prostaglandin saat terjadinya luka dan menyebabkan rasa sakit serta peradangan. Ketika kerja enzim COX terhalangi, maka produksi prostaglandin lebih sedikit, sehingga rasa sakit dan peradangan akan berkurang dan meningkatkan pelepasan panas supaya suhu tubuh normal.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'19','Name'=>'Alco','ImageUrl'=>'19.jpg','Desc'=>'Alco Oral Drop merupakan obat untuk meringankan gejala flu yang disebabkan oleh alergi pada saluran pernapasan atas.','Brand'=>'Alco(Interbat.)','Type'=>'Antihistamin – Dekongestan','AvgPrice'=>'Rp 96.624,- / Botol','General'=>' Alco Oral Drop merupakan obat untuk meringankan gejala flu yang disebabkan oleh alergi pada saluran pernapasan atas. Alco Oral Drop mengandung zat aktif Pseudoephedrin HCl yaitu zat aktif golongan simpatomimetik yang memiliki aktivitas sebagai nasal dekongestan, stimulant, dan wakefulness promoting agent. Senyawa ini bekerja dengan mengecilkan pembuluh darah untuk mengurangi pembengkakan dan penyumbatan terutama pada saluran pernapasan bagian atas. ','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'20','Name'=>'Alerfed, 60mL','ImageUrl'=>'20.jpg','Desc'=>'Alerfed digunakan untuk meredakan gejala gangguan saluran nafas atas seperti rhinitis alergi yaitu adanya inflamasi pada hidung akibat reaksi alergi yang ditandai dengan hidung berair atau tersumbat.','Brand'=>'Alerfed, 60mL(GUARDIAN PHARMATAMA)','Type'=>'Antihistamin – Dekongestan','AvgPrice'=>'Rp 32.208,- / Botol','General'=>'Alerfed syrup diproduksi oleh PT. Guardian Pharmatama dan telah terdaftar pada BPOM. Pada setiap 5ml Alerfed syrup mengandung 1,25mg triprolidine HCl dan 30mg pseudoephedrine HCl. Alerfed digunakan untuk meredakan gejala gangguan saluran nafas atas seperti rhinitis alergi yaitu adanya inflamasi pada hidung akibat reaksi alergi yang ditandai dengan hidung berair atau tersumbat. Alerfed tidak untuk diberikan pada pasien yang memiliki riwayat hipertensi berat dan asma bronkial.','created_at'=>DB::raw('NOW()')),
         
            array('Id'=>'21','Name'=>'Lapifed expectorant,60mL','ImageUrl'=>'21.png','Desc'=>'Lapifed sirup merupakan obat flu yang terdiri dari kombinasi antihistamin dan dekongestan.','Brand'=>'Lapifed expectorant,60mL(LAPI)','Type'=>'Antihistamin – Dekongestan','AvgPrice'=>'Rp 29.524,- / Botol','General'=>'Lapifed sirup merupakan obat flu yang terdiri dari kombinasi antihistamin dan dekongestan. Produk ini dapat meringankan bersin-bersin, hidung gatal dan berair, flu, hidung mampet, commond cold, dan pilek yang disebabkan karena alergi. ','created_at'=>DB::raw('NOW()')),
         
            



        );
 
         //MASUKKAN DATA KE DATABASE
         DB::table('drugs')->insert($arrdrugs);
    }
}
